[workspace]
members = ["bananas-server", "bananas-helper"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["rubeniskov <me@rubeniskov.com>"]
license = "MIT"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.7"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
