SUMMARY = "BanaNAS web admin: bananas-server (HTTP UI) + bananas-helper (root)"
DESCRIPTION = "Two-binary Rust workspace for the BanaNAS admin UI. \
The unprivileged HTTP daemon listens on :8080 and reaches a small \
root-owned helper over a Unix socket for tightly-scoped operations \
(NFS exports rewrite, group management)."

# WIP: This recipe is a stub for future integration. Yocto's cargo bbclass
# requires --offline + --frozen, which means every crate dependency from
# Cargo.lock must be enumerated in SRC_URI as a `crate://` URI (50+ entries
# auto-generated by `cargo bitbake` or similar). Until that's wired up, the
# Rust crates build locally with `cargo build --release` and the binaries
# are deployed manually for testing.
#
# Not yet referenced from IMAGE_INSTALL; do not add until SRC_URI is filled
# in.

LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"

# In-tree workspace: kas materialises poky/ at the bananas repo root, so
# COREBASE/.. is the workspace containing Cargo.toml + crates/.
inherit cargo externalsrc systemd useradd

EXTERNALSRC = "${COREBASE}/.."
EXTERNALSRC_BUILD = "${WORKDIR}/build"

CARGO_BUILD_FLAGS = "--release --workspace --locked"

FILESEXTRAPATHS:prepend := "${THISDIR}/files:"
SRC_URI = "file://bananas-helper.service \
           file://bananas-server.service"

SYSTEMD_SERVICE:${PN} = "bananas-helper.service bananas-server.service"
SYSTEMD_AUTO_ENABLE = "enable"

USERADD_PACKAGES = "${PN}"
GROUPADD_PARAM:${PN} = "-r bananas"
USERADD_PARAM:${PN} = "-r -g bananas -d /var/lib/bananas -s /sbin/nologin \
                       -c 'BanaNAS web admin' bananas"

do_install:append() {
    install -d ${D}${systemd_system_unitdir}
    install -m 0644 ${WORKDIR}/bananas-helper.service ${D}${systemd_system_unitdir}/
    install -m 0644 ${WORKDIR}/bananas-server.service ${D}${systemd_system_unitdir}/
}

FILES:${PN} += "${systemd_system_unitdir}/bananas-helper.service \
                ${systemd_system_unitdir}/bananas-server.service"
