#@TYPE: Machine
#@NAME: Banana Pro
#@DESCRIPTION: Machine config for the LeMaker Banana Pro / BPI-M1+ (Allwinner A20)

require conf/machine/include/sun7i.inc

KERNEL_DEVICETREE = "allwinner/sun7i-a20-bananapro.dtb"
UBOOT_MACHINE = "Bananapro_defconfig"
