# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "bananas"
BBFILE_PATTERN_bananas := "^${LAYERDIR}/"
BBFILE_PRIORITY_bananas = "8"

LAYERDEPENDS_bananas = "core openembedded-layer meta-python networking-layer filesystems-layer"
LAYERSERIES_COMPAT_bananas = "scarthgap nanbield mickledore kirkstone"
